// src/components/Cart.tsx
import * as React from 'react';
import '../styles/Cart.scss';
import { IProduct } from '../types';

export interface ICartProps {
  products: IProduct[];
  total: number;
}

export default function Cart({ products, total }: any){
  return(
    <section className="cart">
      <h3>Meu Carrinho</h3>
      <table>
        <thead>
          <tr>
            <th>Produto</th>
            <th>Quantidade</th>
            <th>Preço</th>
          </tr>
        </thead>
        <tbody>
          {
            products.length > 0 ?
            products.map(
              (product: any, index: number) => (
                <tr key={index}>
                  <td>{product.name}</td>
                  <td>{product.quantity}</td>
                  <td>R${product.price}</td>
                </tr>
              )
            ) : <tr><td>Não existem produtos no seu carrinho!</td></tr>
          }
          <tr>
            <td colSpan={2}>Total</td>
            <td>R${total}</td>
          </tr>
        </tbody>
      </table>
    </section>
  );
}

// src/components/Cart.vue
<template>
  <div class="cart">
    <h1 class="title">Carrinho</h1>
    <p v-show="!products.length">
      <i>Seu carrinho está vazio!</i>
      <router-link to="/">Go shopping</router-link>
    </p>
    <table class="table is-striped" v-show="products.length">
      <thead>
        <tr>
          <td>Nome</td>
          <td>Preço</td>
          <td>Quantidade</td>
        </tr>
      </thead>
      <tbody>
        <tr v-for="product in products" :key="product.id">
            <td>{{ product.name }}</td>
            <td>${{ product.price }}</td>
            <td>{{ product.quantity }}</td>
          </tr>
          <tr>
            <td><b>Total:</b></td>
            <td></td>
            <td><b>R${{ total }}</b></td>
          </tr>
      </tbody>
</table>
    <p><button v-show="products.length" class='button is-primary' @click='checkout'>Checkout</button></p>
  </div>
</template>
<script>
import { mapGetters } from 'vuex'
export default {
  computed: {
    ...mapGetters({
      products: 'cartProducts'
    }),
    total () {
      return this.products.reduce((total, p) => {
        return total + p.price * p.quantity
      }, 0)
    }
  },
  methods: {
    checkout(){
      alert('Total R$' + this.total)
    }
  }
}
</script>
